Repository Team-5A/DjangoJam, pull requests merged in 2024-03, with the labels that each got.

#8 Fix : Amended django_jam_template_tags.py
  .idea/workspace.xml
  django_jam_app/templatetags/django_jam_template_tags.py
Labels: bug

#21 Feat : Added Likes/dislikes
  .idea/workspace.xml
  django_jam_app/urls.py
  django_jam_app/views.py
  static/JS/like_dislike.js
  static/JS/playback.js
  templates/django_jam_app/base.html
  templates/django_jam_app/tune_player.html
  templates/django_jam_app/tunes.html
Labels: enhancement

#26 Profile Total Likes and Self Liked
  .idea/workspace.xml
  django_jam_app/views.py
Labels: enhancement

#27 Fix : Username using capitals not being able to log in.
  .idea/workspace.xml
  django_jam_app/views.py
Labels: bug

#22 Feat : Note operation
  .idea/workspace.xml
  django_jam_app/models.py
  django_jam_app/notes.py
  django_jam_app/urls.py
  django_jam_app/views.py
  migrate.py
  render_template.py
  templates/django_jam_app/add_tune.html
  templates/django_jam_app/render_template.html
Labels: enhancement

#32 Chore : Re pull request for population.py update. Due to workflow issues
  .idea/workspace.xml
  populate_jam.py
Labels: duplicate, enhancement

#33 Fix : Added create_super_user.py script that gives admin a profile
  .idea/workspace.xml
  create_super_user.py
  migrate.py
Labels: bug

#39 Feat: added test cases for templates, views, and forms
  django_jam_app/__pycache__/__init__.cpython-311.pyc
  django_jam_app/__pycache__/apps.cpython-311.pyc
  django_jam_app/__pycache__/models.cpython-311.pyc
  django_jam_app/tests.py
  django_jam_project/__pycache__/__init__.cpython-311.pyc
  django_jam_project/__pycache__/settings.cpython-311.pyc
Labels: enhancement
